# Pull base image
FROM resin/rpi-raspbian:jessie-20161207
MAINTAINER Jason Yang

# Install dependencies
RUN apt-get update && apt-get install -y \
    make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl llvm libncurses5-dev libncursesw5-dev xz-utils && \
    rm -rf /var/lib/apt/lists/*

# Install Python 3.5.2
RUN curl https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz | tar -xz && \
    cd Python-3.5.2 && \
    ./configure && \
    make -j $(getconf _NPROCESSORS_ONLN) && \
    make install && \
    cd ..; rm -rf ./Python-3.5.2

RUN mkdir /web
WORKDIR /web

ADD requirements.txt /web
RUN pip3 install -r requirements.txt

ENV FLASK_APP app/wsgi.py

VOLUME ["/web"]

# Expose ports.
EXPOSE 5000

# Define default command
CMD ["bash"]