version: '2'
services:
  web:
    build: ./web
    command: gunicorn -w 2 -k egg:meinheld#gunicorn_worker -b :5000 app.wsgi:app
    volumes:
      - ./web/:/web
    ports:
      - "5000:5000"
    restart: always
  proxy:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    depends_on:
      - web
